
set nocompatible    
filetype off


"===== 编辑 =====
"不使用兼容 vi 的操作
set nocp
"打开 vim 的状态栏标尺
set ru
"显示行号
set nu
"设置 tab 长度设置为 4
set tabstop=4
"设置自动缩进为 4
set shiftwidth=4
"编辑时将所有 tab 替换为空格
set et
"搜索时高亮显示
set hls
"关键字上色
syntax on
"覆盖文件时不备份
set nobackup
"突出显示当前行
"set cursorline
"在右下角显示光标位置的状态行
set ruler
"自动缩进
set autoindent
"可以删除当前头, 前一行的尾
set backspace=indent,eol,start
"设置当前字符编码 cp936 是 gbk
set encoding=utf-8
set fileencodings=utf-8,chinese,latin-1

"===== 断行 =====
"不在单词中断行
set lbr
"打开断行对亚洲语言的支持
"m表示允许两个汉字间断行
"B表示两行合为一行时, 汉字间不补空格
set fo+=mB
"自动换行, set nowrap 关闭
set wrap

"===== 编码 =====
"显示括号配对的情况
set sm
"打开 c/c++ 风格的自动缩进
set cin
"设定 C/C++ 风格自动缩进的选项
set cino=:0g0t0(sus
"打开普通文件类型的自动缩进
set autoindent
"开启真彩色
set termguicolors

"===== 配色 =====
"使用 torte 配色
"colo torte
colo janah
"colo seoul256
"colo railscasts